### ISSUE TITLE
"node_modules" path location problem

### ISSUE THREAD

**Issue by mwmw7** [rxaviers/cldr-data-bower#2]
bower postinstall   node ./node_modules/cldr-data-downloader/bin/download.js -i bower_components/cldr-data/index.json -o bower_components/cldr-data/
bower postinstall   module.js:340
bower postinstall       throw err;
bower postinstall             ^
bower postinstall   Error: Cannot find module '/home/hosoup/tmp/i18n/cldr-data-bower/node_modules/cldr-data-downloader/bin/download.js'
bower postinstall       at Function.Module._resolveFilename (module.js:338:15)
bower postinstall       at Function.Module._load (module.js:280:25)
bower postinstall       at Function.Module.runMain (module.js:497:10)
bower postinstall       at startup (node.js:119:16)
bower postinstall       at node.js:902:3
bower ECMDERR       Failed to execute "node ./node_modules/cldr-data-downloader/bin/download.js -i bower_components/cldr-data/index.json -o bower_components/cldr-data/", exit code of #8

Additional error details:
module.js:340
    throw err;
          ^
Error: Cannot find module '/home/hosoup/tmp/i18n/cldr-data-bower/node_modules/cldr-data-downloader/bin/download.js'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3

after this command -> "preinstall": "npm install cldr-data-downloader",

"node_modules " is made  in "../"

**Comment by rxaviers** [comment]
Thanks for filing this issue. But, I could not find any problem with cldr-data-bower given your message. Shouldn't you update your .bowerrc according to your "../node_modules"? E.g., `node ../node_modules/...`
